package internal

import (
	"encoding/json"
	"testing"
)

func Test(t *testing.T) {
	file := `{
  "action": "synchronize",
  "after": "2ecf31ecd960258770c108855172dd5cfbdd8479",
  "before": "c361397d2721b18fcc30750a5866c23c17b4ea1e",
  "number": 271,
  "organization": {
    "avatar_url": "https://avatars.githubusercontent.com/u/1391778?v=4",
    "description": "Public sector technology delivery experts",
    "events_url": "https://api.github.com/orgs/madetech/events",
    "hooks_url": "https://api.github.com/orgs/madetech/hooks",
    "id": 1391778,
    "issues_url": "https://api.github.com/orgs/madetech/issues",
    "login": "madetech",
    "members_url": "https://api.github.com/orgs/madetech/members{/member}",
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTE3Nzg=",
    "public_members_url": "https://api.github.com/orgs/madetech/public_members{/member}",
    "repos_url": "https://api.github.com/orgs/madetech/repos",
    "url": "https://api.github.com/orgs/madetech"
  },
  "pull_request": {
    "_links": {
      "comments": {
        "href": "https://api.github.com/repos/madetech/saas-platform/issues/271/comments"
      },
      "commits": {
        "href": "https://api.github.com/repos/madetech/saas-platform/pulls/271/commits"
      },
      "html": {
        "href": "https://github.com/madetech/saas-platform/pull/271"
      },
      "issue": {
        "href": "https://api.github.com/repos/madetech/saas-platform/issues/271"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/madetech/saas-platform/pulls/comments{/number}"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/madetech/saas-platform/pulls/271/comments"
      },
      "self": {
        "href": "https://api.github.com/repos/madetech/saas-platform/pulls/271"
      },
      "statuses": {
        "href": "https://api.github.com/repos/madetech/saas-platform/statuses/2ecf31ecd960258770c108855172dd5cfbdd8479"
      }
    },
    "active_lock_reason": null,
    "additions": 0,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "auto_merge": null,
    "base": {
      "label": "madetech:main",
      "ref": "main",
      "repo": {
        "allow_auto_merge": false,
        "allow_forking": true,
        "allow_merge_commit": false,
        "allow_rebase_merge": true,
        "allow_squash_merge": false,
        "allow_update_branch": false,
        "archive_url": "https://api.github.com/repos/madetech/saas-platform/{archive_format}{/ref}",
        "archived": false,
        "assignees_url": "https://api.github.com/repos/madetech/saas-platform/assignees{/user}",
        "blobs_url": "https://api.github.com/repos/madetech/saas-platform/git/blobs{/sha}",
        "branches_url": "https://api.github.com/repos/madetech/saas-platform/branches{/branch}",
        "clone_url": "https://github.com/madetech/saas-platform.git",
        "collaborators_url": "https://api.github.com/repos/madetech/saas-platform/collaborators{/collaborator}",
        "comments_url": "https://api.github.com/repos/madetech/saas-platform/comments{/number}",
        "commits_url": "https://api.github.com/repos/madetech/saas-platform/commits{/sha}",
        "compare_url": "https://api.github.com/repos/madetech/saas-platform/compare/{base}...{head}",
        "contents_url": "https://api.github.com/repos/madetech/saas-platform/contents/{+path}",
        "contributors_url": "https://api.github.com/repos/madetech/saas-platform/contributors",
        "created_at": "2022-06-24T14:18:36Z",
        "default_branch": "main",
        "delete_branch_on_merge": true,
        "deployments_url": "https://api.github.com/repos/madetech/saas-platform/deployments",
        "description": "R&D SaaS Platform",
        "disabled": false,
        "downloads_url": "https://api.github.com/repos/madetech/saas-platform/downloads",
        "events_url": "https://api.github.com/repos/madetech/saas-platform/events",
        "fork": false,
        "forks": 0,
        "forks_count": 0,
        "forks_url": "https://api.github.com/repos/madetech/saas-platform/forks",
        "full_name": "madetech/saas-platform",
        "git_commits_url": "https://api.github.com/repos/madetech/saas-platform/git/commits{/sha}",
        "git_refs_url": "https://api.github.com/repos/madetech/saas-platform/git/refs{/sha}",
        "git_tags_url": "https://api.github.com/repos/madetech/saas-platform/git/tags{/sha}",
        "git_url": "git://github.com/madetech/saas-platform.git",
        "has_discussions": false,
        "has_downloads": true,
        "has_issues": false,
        "has_pages": false,
        "has_projects": false,
        "has_wiki": false,
        "homepage": "",
        "hooks_url": "https://api.github.com/repos/madetech/saas-platform/hooks",
        "html_url": "https://github.com/madetech/saas-platform",
        "id": 507037032,
        "is_template": false,
        "issue_comment_url": "https://api.github.com/repos/madetech/saas-platform/issues/comments{/number}",
        "issue_events_url": "https://api.github.com/repos/madetech/saas-platform/issues/events{/number}",
        "issues_url": "https://api.github.com/repos/madetech/saas-platform/issues{/number}",
        "keys_url": "https://api.github.com/repos/madetech/saas-platform/keys{/key_id}",
        "labels_url": "https://api.github.com/repos/madetech/saas-platform/labels{/name}",
        "language": "Shell",
        "languages_url": "https://api.github.com/repos/madetech/saas-platform/languages",
        "license": null,
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE",
        "merges_url": "https://api.github.com/repos/madetech/saas-platform/merges",
        "milestones_url": "https://api.github.com/repos/madetech/saas-platform/milestones{/number}",
        "mirror_url": null,
        "name": "saas-platform",
        "node_id": "R_kgDOHjjFaA",
        "notifications_url": "https://api.github.com/repos/madetech/saas-platform/notifications{?since,all,participating}",
        "open_issues": 1,
        "open_issues_count": 1,
        "owner": {
          "avatar_url": "https://avatars.githubusercontent.com/u/1391778?v=4",
          "events_url": "https://api.github.com/users/madetech/events{/privacy}",
          "followers_url": "https://api.github.com/users/madetech/followers",
          "following_url": "https://api.github.com/users/madetech/following{/other_user}",
          "gists_url": "https://api.github.com/users/madetech/gists{/gist_id}",
          "gravatar_id": "",
          "html_url": "https://github.com/madetech",
          "id": 1391778,
          "login": "madetech",
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTE3Nzg=",
          "organizations_url": "https://api.github.com/users/madetech/orgs",
          "received_events_url": "https://api.github.com/users/madetech/received_events",
          "repos_url": "https://api.github.com/users/madetech/repos",
          "site_admin": false,
          "starred_url": "https://api.github.com/users/madetech/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/madetech/subscriptions",
          "type": "Organization",
          "url": "https://api.github.com/users/madetech"
        },
        "private": true,
        "pulls_url": "https://api.github.com/repos/madetech/saas-platform/pulls{/number}",
        "pushed_at": "2022-11-11T15:51:27Z",
        "releases_url": "https://api.github.com/repos/madetech/saas-platform/releases{/id}",
        "size": 1613,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "ssh_url": "git@github.com:madetech/saas-platform.git",
        "stargazers_count": 0,
        "stargazers_url": "https://api.github.com/repos/madetech/saas-platform/stargazers",
        "statuses_url": "https://api.github.com/repos/madetech/saas-platform/statuses/{sha}",
        "subscribers_url": "https://api.github.com/repos/madetech/saas-platform/subscribers",
        "subscription_url": "https://api.github.com/repos/madetech/saas-platform/subscription",
        "svn_url": "https://github.com/madetech/saas-platform",
        "tags_url": "https://api.github.com/repos/madetech/saas-platform/tags",
        "teams_url": "https://api.github.com/repos/madetech/saas-platform/teams",
        "topics": [],
        "trees_url": "https://api.github.com/repos/madetech/saas-platform/git/trees{/sha}",
        "updated_at": "2022-09-13T09:19:37Z",
        "url": "https://api.github.com/repos/madetech/saas-platform",
        "use_squash_pr_title_as_default": false,
        "visibility": "private",
        "watchers": 0,
        "watchers_count": 0,
        "web_commit_signoff_required": false
      },
      "sha": "e7ea92e175725b73b6c0a838661ede558fba502e",
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1391778?v=4",
        "events_url": "https://api.github.com/users/madetech/events{/privacy}",
        "followers_url": "https://api.github.com/users/madetech/followers",
        "following_url": "https://api.github.com/users/madetech/following{/other_user}",
        "gists_url": "https://api.github.com/users/madetech/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/madetech",
        "id": 1391778,
        "login": "madetech",
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTE3Nzg=",
        "organizations_url": "https://api.github.com/users/madetech/orgs",
        "received_events_url": "https://api.github.com/users/madetech/received_events",
        "repos_url": "https://api.github.com/users/madetech/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/madetech/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/madetech/subscriptions",
        "type": "Organization",
        "url": "https://api.github.com/users/madetech"
      }
    },
    "body": null,
    "changed_files": 0,
    "closed_at": null,
    "comments": 0,
    "comments_url": "https://api.github.com/repos/madetech/saas-platform/issues/271/comments",
    "commits": 6,
    "commits_url": "https://api.github.com/repos/madetech/saas-platform/pulls/271/commits",
    "created_at": "2022-11-10T14:39:25Z",
    "deletions": 0,
    "diff_url": "https://github.com/madetech/saas-platform/pull/271.diff",
    "draft": false,
    "head": {
      "label": "madetech:sparkling-dependencies-test",
      "ref": "sparkling-dependencies-test",
      "repo": {
        "allow_auto_merge": false,
        "allow_forking": true,
        "allow_merge_commit": false,
        "allow_rebase_merge": true,
        "allow_squash_merge": false,
        "allow_update_branch": false,
        "archive_url": "https://api.github.com/repos/madetech/saas-platform/{archive_format}{/ref}",
        "archived": false,
        "assignees_url": "https://api.github.com/repos/madetech/saas-platform/assignees{/user}",
        "blobs_url": "https://api.github.com/repos/madetech/saas-platform/git/blobs{/sha}",
        "branches_url": "https://api.github.com/repos/madetech/saas-platform/branches{/branch}",
        "clone_url": "https://github.com/madetech/saas-platform.git",
        "collaborators_url": "https://api.github.com/repos/madetech/saas-platform/collaborators{/collaborator}",
        "comments_url": "https://api.github.com/repos/madetech/saas-platform/comments{/number}",
        "commits_url": "https://api.github.com/repos/madetech/saas-platform/commits{/sha}",
        "compare_url": "https://api.github.com/repos/madetech/saas-platform/compare/{base}...{head}",
        "contents_url": "https://api.github.com/repos/madetech/saas-platform/contents/{+path}",
        "contributors_url": "https://api.github.com/repos/madetech/saas-platform/contributors",
        "created_at": "2022-06-24T14:18:36Z",
        "default_branch": "main",
        "delete_branch_on_merge": true,
        "deployments_url": "https://api.github.com/repos/madetech/saas-platform/deployments",
        "description": "R&D SaaS Platform",
        "disabled": false,
        "downloads_url": "https://api.github.com/repos/madetech/saas-platform/downloads",
        "events_url": "https://api.github.com/repos/madetech/saas-platform/events",
        "fork": false,
        "forks": 0,
        "forks_count": 0,
        "forks_url": "https://api.github.com/repos/madetech/saas-platform/forks",
        "full_name": "madetech/saas-platform",
        "git_commits_url": "https://api.github.com/repos/madetech/saas-platform/git/commits{/sha}",
        "git_refs_url": "https://api.github.com/repos/madetech/saas-platform/git/refs{/sha}",
        "git_tags_url": "https://api.github.com/repos/madetech/saas-platform/git/tags{/sha}",
        "git_url": "git://github.com/madetech/saas-platform.git",
        "has_discussions": false,
        "has_downloads": true,
        "has_issues": false,
        "has_pages": false,
        "has_projects": false,
        "has_wiki": false,
        "homepage": "",
        "hooks_url": "https://api.github.com/repos/madetech/saas-platform/hooks",
        "html_url": "https://github.com/madetech/saas-platform",
        "id": 507037032,
        "is_template": false,
        "issue_comment_url": "https://api.github.com/repos/madetech/saas-platform/issues/comments{/number}",
        "issue_events_url": "https://api.github.com/repos/madetech/saas-platform/issues/events{/number}",
        "issues_url": "https://api.github.com/repos/madetech/saas-platform/issues{/number}",
        "keys_url": "https://api.github.com/repos/madetech/saas-platform/keys{/key_id}",
        "labels_url": "https://api.github.com/repos/madetech/saas-platform/labels{/name}",
        "language": "Shell",
        "languages_url": "https://api.github.com/repos/madetech/saas-platform/languages",
        "license": null,
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE",
        "merges_url": "https://api.github.com/repos/madetech/saas-platform/merges",
        "milestones_url": "https://api.github.com/repos/madetech/saas-platform/milestones{/number}",
        "mirror_url": null,
        "name": "saas-platform",
        "node_id": "R_kgDOHjjFaA",
        "notifications_url": "https://api.github.com/repos/madetech/saas-platform/notifications{?since,all,participating}",
        "open_issues": 1,
        "open_issues_count": 1,
        "owner": {
          "avatar_url": "https://avatars.githubusercontent.com/u/1391778?v=4",
          "events_url": "https://api.github.com/users/madetech/events{/privacy}",
          "followers_url": "https://api.github.com/users/madetech/followers",
          "following_url": "https://api.github.com/users/madetech/following{/other_user}",
          "gists_url": "https://api.github.com/users/madetech/gists{/gist_id}",
          "gravatar_id": "",
          "html_url": "https://github.com/madetech",
          "id": 1391778,
          "login": "madetech",
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTE3Nzg=",
          "organizations_url": "https://api.github.com/users/madetech/orgs",
          "received_events_url": "https://api.github.com/users/madetech/received_events",
          "repos_url": "https://api.github.com/users/madetech/repos",
          "site_admin": false,
          "starred_url": "https://api.github.com/users/madetech/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/madetech/subscriptions",
          "type": "Organization",
          "url": "https://api.github.com/users/madetech"
        },
        "private": true,
        "pulls_url": "https://api.github.com/repos/madetech/saas-platform/pulls{/number}",
        "pushed_at": "2022-11-11T15:51:27Z",
        "releases_url": "https://api.github.com/repos/madetech/saas-platform/releases{/id}",
        "size": 1613,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "ssh_url": "git@github.com:madetech/saas-platform.git",
        "stargazers_count": 0,
        "stargazers_url": "https://api.github.com/repos/madetech/saas-platform/stargazers",
        "statuses_url": "https://api.github.com/repos/madetech/saas-platform/statuses/{sha}",
        "subscribers_url": "https://api.github.com/repos/madetech/saas-platform/subscribers",
        "subscription_url": "https://api.github.com/repos/madetech/saas-platform/subscription",
        "svn_url": "https://github.com/madetech/saas-platform",
        "tags_url": "https://api.github.com/repos/madetech/saas-platform/tags",
        "teams_url": "https://api.github.com/repos/madetech/saas-platform/teams",
        "topics": [],
        "trees_url": "https://api.github.com/repos/madetech/saas-platform/git/trees{/sha}",
        "updated_at": "2022-09-13T09:19:37Z",
        "url": "https://api.github.com/repos/madetech/saas-platform",
        "use_squash_pr_title_as_default": false,
        "visibility": "private",
        "watchers": 0,
        "watchers_count": 0,
        "web_commit_signoff_required": false
      },
      "sha": "2ecf31ecd960258770c108855172dd5cfbdd8479",
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1391778?v=4",
        "events_url": "https://api.github.com/users/madetech/events{/privacy}",
        "followers_url": "https://api.github.com/users/madetech/followers",
        "following_url": "https://api.github.com/users/madetech/following{/other_user}",
        "gists_url": "https://api.github.com/users/madetech/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/madetech",
        "id": 1391778,
        "login": "madetech",
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTE3Nzg=",
        "organizations_url": "https://api.github.com/users/madetech/orgs",
        "received_events_url": "https://api.github.com/users/madetech/received_events",
        "repos_url": "https://api.github.com/users/madetech/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/madetech/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/madetech/subscriptions",
        "type": "Organization",
        "url": "https://api.github.com/users/madetech"
      }
    },
    "html_url": "https://github.com/madetech/saas-platform/pull/271",
    "id": 1117820941,
    "issue_url": "https://api.github.com/repos/madetech/saas-platform/issues/271",
    "labels": [],
    "locked": false,
    "maintainer_can_modify": false,
    "merge_commit_sha": "7e1fc6f0bd22e13c8d7085a0d3f10631b57ccb10",
    "mergeable": null,
    "mergeable_state": "unknown",
    "merged": false,
    "merged_at": null,
    "merged_by": null,
    "milestone": null,
    "node_id": "PR_kwDOHjjFaM5CoJgN",
    "number": 271,
    "patch_url": "https://github.com/madetech/saas-platform/pull/271.patch",
    "rebaseable": null,
    "requested_reviewers": [],
    "requested_teams": [],
    "review_comment_url": "https://api.github.com/repos/madetech/saas-platform/pulls/comments{/number}",
    "review_comments": 0,
    "review_comments_url": "https://api.github.com/repos/madetech/saas-platform/pulls/271/comments",
    "state": "open",
    "statuses_url": "https://api.github.com/repos/madetech/saas-platform/statuses/2ecf31ecd960258770c108855172dd5cfbdd8479",
    "title": "Some changes",
    "updated_at": "2022-11-11T15:51:27Z",
    "url": "https://api.github.com/repos/madetech/saas-platform/pulls/271",
    "user": {
      "avatar_url": "https://avatars.githubusercontent.com/u/1889973?v=4",
      "events_url": "https://api.github.com/users/craigjbass/events{/privacy}",
      "followers_url": "https://api.github.com/users/craigjbass/followers",
      "following_url": "https://api.github.com/users/craigjbass/following{/other_user}",
      "gists_url": "https://api.github.com/users/craigjbass/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/craigjbass",
      "id": 1889973,
      "login": "craigjbass",
      "node_id": "MDQ6VXNlcjE4ODk5NzM=",
      "organizations_url": "https://api.github.com/users/craigjbass/orgs",
      "received_events_url": "https://api.github.com/users/craigjbass/received_events",
      "repos_url": "https://api.github.com/users/craigjbass/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/craigjbass/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/craigjbass/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/craigjbass"
    }
  },
  "repository": {
    "allow_forking": true,
    "archive_url": "https://api.github.com/repos/madetech/saas-platform/{archive_format}{/ref}",
    "archived": false,
    "assignees_url": "https://api.github.com/repos/madetech/saas-platform/assignees{/user}",
    "blobs_url": "https://api.github.com/repos/madetech/saas-platform/git/blobs{/sha}",
    "branches_url": "https://api.github.com/repos/madetech/saas-platform/branches{/branch}",
    "clone_url": "https://github.com/madetech/saas-platform.git",
    "collaborators_url": "https://api.github.com/repos/madetech/saas-platform/collaborators{/collaborator}",
    "comments_url": "https://api.github.com/repos/madetech/saas-platform/comments{/number}",
    "commits_url": "https://api.github.com/repos/madetech/saas-platform/commits{/sha}",
    "compare_url": "https://api.github.com/repos/madetech/saas-platform/compare/{base}...{head}",
    "contents_url": "https://api.github.com/repos/madetech/saas-platform/contents/{+path}",
    "contributors_url": "https://api.github.com/repos/madetech/saas-platform/contributors",
    "created_at": "2022-06-24T14:18:36Z",
    "default_branch": "main",
    "deployments_url": "https://api.github.com/repos/madetech/saas-platform/deployments",
    "description": "R&D SaaS Platform",
    "disabled": false,
    "downloads_url": "https://api.github.com/repos/madetech/saas-platform/downloads",
    "events_url": "https://api.github.com/repos/madetech/saas-platform/events",
    "fork": false,
    "forks": 0,
    "forks_count": 0,
    "forks_url": "https://api.github.com/repos/madetech/saas-platform/forks",
    "full_name": "madetech/saas-platform",
    "git_commits_url": "https://api.github.com/repos/madetech/saas-platform/git/commits{/sha}",
    "git_refs_url": "https://api.github.com/repos/madetech/saas-platform/git/refs{/sha}",
    "git_tags_url": "https://api.github.com/repos/madetech/saas-platform/git/tags{/sha}",
    "git_url": "git://github.com/madetech/saas-platform.git",
    "has_discussions": false,
    "has_downloads": true,
    "has_issues": false,
    "has_pages": false,
    "has_projects": false,
    "has_wiki": false,
    "homepage": "",
    "hooks_url": "https://api.github.com/repos/madetech/saas-platform/hooks",
    "html_url": "https://github.com/madetech/saas-platform",
    "id": 507037032,
    "is_template": false,
    "issue_comment_url": "https://api.github.com/repos/madetech/saas-platform/issues/comments{/number}",
    "issue_events_url": "https://api.github.com/repos/madetech/saas-platform/issues/events{/number}",
    "issues_url": "https://api.github.com/repos/madetech/saas-platform/issues{/number}",
    "keys_url": "https://api.github.com/repos/madetech/saas-platform/keys{/key_id}",
    "labels_url": "https://api.github.com/repos/madetech/saas-platform/labels{/name}",
    "language": "Shell",
    "languages_url": "https://api.github.com/repos/madetech/saas-platform/languages",
    "license": null,
    "merges_url": "https://api.github.com/repos/madetech/saas-platform/merges",
    "milestones_url": "https://api.github.com/repos/madetech/saas-platform/milestones{/number}",
    "mirror_url": null,
    "name": "saas-platform",
    "node_id": "R_kgDOHjjFaA",
    "notifications_url": "https://api.github.com/repos/madetech/saas-platform/notifications{?since,all,participating}",
    "open_issues": 1,
    "open_issues_count": 1,
    "owner": {
      "avatar_url": "https://avatars.githubusercontent.com/u/1391778?v=4",
      "events_url": "https://api.github.com/users/madetech/events{/privacy}",
      "followers_url": "https://api.github.com/users/madetech/followers",
      "following_url": "https://api.github.com/users/madetech/following{/other_user}",
      "gists_url": "https://api.github.com/users/madetech/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/madetech",
      "id": 1391778,
      "login": "madetech",
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzOTE3Nzg=",
      "organizations_url": "https://api.github.com/users/madetech/orgs",
      "received_events_url": "https://api.github.com/users/madetech/received_events",
      "repos_url": "https://api.github.com/users/madetech/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/madetech/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/madetech/subscriptions",
      "type": "Organization",
      "url": "https://api.github.com/users/madetech"
    },
    "private": true,
    "pulls_url": "https://api.github.com/repos/madetech/saas-platform/pulls{/number}",
    "pushed_at": "2022-11-11T15:51:27Z",
    "releases_url": "https://api.github.com/repos/madetech/saas-platform/releases{/id}",
    "size": 1613,
    "ssh_url": "git@github.com:madetech/saas-platform.git",
    "stargazers_count": 0,
    "stargazers_url": "https://api.github.com/repos/madetech/saas-platform/stargazers",
    "statuses_url": "https://api.github.com/repos/madetech/saas-platform/statuses/{sha}",
    "subscribers_url": "https://api.github.com/repos/madetech/saas-platform/subscribers",
    "subscription_url": "https://api.github.com/repos/madetech/saas-platform/subscription",
    "svn_url": "https://github.com/madetech/saas-platform",
    "tags_url": "https://api.github.com/repos/madetech/saas-platform/tags",
    "teams_url": "https://api.github.com/repos/madetech/saas-platform/teams",
    "topics": [],
    "trees_url": "https://api.github.com/repos/madetech/saas-platform/git/trees{/sha}",
    "updated_at": "2022-09-13T09:19:37Z",
    "url": "https://api.github.com/repos/madetech/saas-platform",
    "visibility": "private",
    "watchers": 0,
    "watchers_count": 0,
    "web_commit_signoff_required": false
  },
  "sender": {
    "avatar_url": "https://avatars.githubusercontent.com/u/1889973?v=4",
    "events_url": "https://api.github.com/users/craigjbass/events{/privacy}",
    "followers_url": "https://api.github.com/users/craigjbass/followers",
    "following_url": "https://api.github.com/users/craigjbass/following{/other_user}",
    "gists_url": "https://api.github.com/users/craigjbass/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/craigjbass",
    "id": 1889973,
    "login": "craigjbass",
    "node_id": "MDQ6VXNlcjE4ODk5NzM=",
    "organizations_url": "https://api.github.com/users/craigjbass/orgs",
    "received_events_url": "https://api.github.com/users/craigjbass/received_events",
    "repos_url": "https://api.github.com/users/craigjbass/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/craigjbass/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/craigjbass/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/craigjbass"
  }
}`

	var data struct {
		Sender struct {
			Login string `json:"login"`
		} `json:"sender"`
		PullRequest struct {
			Number uint32 `json:"number"`
			Title  string `json:"title"`
		} `json:"pull_request"`
		Repository struct {
			FullName string `json:"full_name"`
		} `json:"repository"`
	}
	err := json.Unmarshal([]byte(file), &data)
	if err != nil {
		panic(err)
	}

	if data.Sender.Login != "craigjbass" {
		t.Errorf("Expected %#v got %#v", "craigjbass", data.Sender.Login)
	}

	if data.PullRequest.Number != 271 {
		t.Errorf("Expected %#v got %#v", 0, data.PullRequest.Number)
	}

	if data.Repository.FullName != "madetech/saas-platform" {
		t.Errorf("Expected %#v got %#v", "madetech/saas-platform", data.Repository.FullName)
	}

	if data.PullRequest.Title != "Some changes" {
		t.Errorf("Expected %#v got %#v", "some changes", data.PullRequest.Title)
	}
}
